[package]
name = "nft_asset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
num-complex = "0.4"
imageproc = "0.23.0"
rusttype = "0.9.2"
font-loader = "0.11.0"